GET http://localhost:3035/categories
Content-Type: application/json

###

GET http://localhost:3035/questions
Content-Type: application/json

###

GET http://localhost:3035/mort-subites
Content-Type: application/json

###

GET http://localhost:3035/parties
Content-Type: application/json